### PR TITLE
Fix IDE warnings

### PR DESCRIPTION
**Pull request by mlocati**
This PR fixes a few warnings raised by my IDE

### CODE REVIEW

**Comment by KorvinSzanto** [comment]
Very nice, thank you!
Can your .shim file be moved to individual stubs like we have in [`/.psalm/stubs`](/concrete5/console/tree/main/.psalm/stubs)?

**Comment by mlocati** [comment]
Should I rename them as `.php.stub`?

**Comment by KorvinSzanto** [comment]
I named them `.php.stub`, the psalm docs use `.phpstub`: https://psalm.dev/docs/running_psalm/plugins/authoring_plugins/ It honestly doesn't matter to me what we use as long as we're consistent. Make sure to add them to the psalm.xml as well.

I'm not sure if what you're trying to resolve is resolved by using the stub files, if not maybe we can just have both.

**Comment by mlocati** [comment]
Should I keep the php stub files in the .concrete directory? I'd prefer to have all of them in the same place (.psalm/stubs)

**Comment by KorvinSzanto** [comment]
> Should I keep the php stub files in the .concrete directory? I'd prefer to have all of them in the same place (.psalm/stubs)
If you mean that `index.maintenance.php` then yeah I want that to stay in the `.concrete` directory since it's more of a template than a stub.

If you mean `shim.php` from this PR then yeah I'd prefer those classes in individual files underneath `.psalm/stubs` like the other two stubs are assuming that still fixes the IDE warnings you're mentioning.

**Review by KorvinSzanto — APPROVED** [review]

**Pull request merged**
